# To convert Hex to Int use: CONV(HEX(@VAR), 16, 10)

####################
# Action Bar Types #
####################

SET @ACTION_BAR_TYPE_SPELL     =   0; # 0x00
SET @ACTION_BAR_TYPE_C         =   1; # 0x01
SET @ACTION_BAR_TYPE_EQSET     =  32; # 0x20
SET @ACTION_BAR_TYPE_DROPDOWN  =  48; # 0x30
SET @ACTION_BAR_TYPE_MACRO     =  64; # 0x40
SET @ACTION_BAR_TYPE_CMACRO    = @ACTION_BAR_TYPE_C + @ACTION_BAR_TYPE_MACRO; # 65
SET @ACTION_BAR_TYPE_COMPANION =  80; # 0x50
SET @ACTION_BAR_TYPE_MOUNT     =  96; # 0x60
SET @ACTION_BAR_TYPE_ITEM      = 128; # 0x80

####################
# Action Bar Slots #
####################

SET @ACTION_BAR_1_SLOT_1       =  0;
SET @ACTION_BAR_1_SLOT_2       =  1;
SET @ACTION_BAR_1_SLOT_3       =  2;
SET @ACTION_BAR_1_SLOT_4       =  3;
SET @ACTION_BAR_1_SLOT_5       =  4;
SET @ACTION_BAR_1_SLOT_6       =  5;
SET @ACTION_BAR_1_SLOT_7       =  6;
SET @ACTION_BAR_1_SLOT_8       =  7;
SET @ACTION_BAR_1_SLOT_9       =  8;
SET @ACTION_BAR_1_SLOT_0       =  9;
SET @ACTION_BAR_1_SLOT_MINUS   = 10;
SET @ACTION_BAR_1_SLOT_EQUALS  = 11;

SET @ACTION_BAR_2_SLOT_1       = 12;
SET @ACTION_BAR_2_SLOT_2       = 13;
SET @ACTION_BAR_2_SLOT_3       = 14;
SET @ACTION_BAR_2_SLOT_4       = 15;
SET @ACTION_BAR_2_SLOT_5       = 16;
SET @ACTION_BAR_2_SLOT_6       = 17;
SET @ACTION_BAR_2_SLOT_7       = 18;
SET @ACTION_BAR_2_SLOT_8       = 19;
SET @ACTION_BAR_2_SLOT_9       = 20;
SET @ACTION_BAR_2_SLOT_0       = 21;
SET @ACTION_BAR_2_SLOT_MINUS   = 22;
SET @ACTION_BAR_2_SLOT_EQUALS  = 23;

SET @ACTION_BAR_3_SLOT_1       = 24;
SET @ACTION_BAR_3_SLOT_2       = 25;
SET @ACTION_BAR_3_SLOT_3       = 26;
SET @ACTION_BAR_3_SLOT_4       = 27;
SET @ACTION_BAR_3_SLOT_5       = 28;
SET @ACTION_BAR_3_SLOT_6       = 29;
SET @ACTION_BAR_3_SLOT_7       = 30;
SET @ACTION_BAR_3_SLOT_8       = 31;
SET @ACTION_BAR_3_SLOT_9       = 32;
SET @ACTION_BAR_3_SLOT_0       = 33;
SET @ACTION_BAR_3_SLOT_MINUS   = 34;
SET @ACTION_BAR_3_SLOT_EQUALS  = 35;

SET @ACTION_BAR_4_SLOT_1       = 36;
SET @ACTION_BAR_4_SLOT_2       = 37;
SET @ACTION_BAR_4_SLOT_3       = 38;
SET @ACTION_BAR_4_SLOT_4       = 39;
SET @ACTION_BAR_4_SLOT_5       = 40;
SET @ACTION_BAR_4_SLOT_6       = 41;
SET @ACTION_BAR_4_SLOT_7       = 42;
SET @ACTION_BAR_4_SLOT_8       = 43;
SET @ACTION_BAR_4_SLOT_9       = 44;
SET @ACTION_BAR_4_SLOT_0       = 45;
SET @ACTION_BAR_4_SLOT_MINUS   = 46;
SET @ACTION_BAR_4_SLOT_EQUALS  = 47;

SET @ACTION_BAR_5_SLOT_1       = 48;
SET @ACTION_BAR_5_SLOT_2       = 49;
SET @ACTION_BAR_5_SLOT_3       = 50;
SET @ACTION_BAR_5_SLOT_4       = 51;
SET @ACTION_BAR_5_SLOT_5       = 52;
SET @ACTION_BAR_5_SLOT_6       = 53;
SET @ACTION_BAR_5_SLOT_7       = 54;
SET @ACTION_BAR_5_SLOT_8       = 55;
SET @ACTION_BAR_5_SLOT_9       = 56;
SET @ACTION_BAR_5_SLOT_0       = 57;
SET @ACTION_BAR_5_SLOT_MINUS   = 58;
SET @ACTION_BAR_5_SLOT_EQUALS  = 59;

SET @ACTION_BAR_6_SLOT_1       = 60;
SET @ACTION_BAR_6_SLOT_2       = 61;
SET @ACTION_BAR_6_SLOT_3       = 62;
SET @ACTION_BAR_6_SLOT_4       = 63;
SET @ACTION_BAR_6_SLOT_5       = 64;
SET @ACTION_BAR_6_SLOT_6       = 65;
SET @ACTION_BAR_6_SLOT_7       = 66;
SET @ACTION_BAR_6_SLOT_8       = 67;
SET @ACTION_BAR_6_SLOT_9       = 68;
SET @ACTION_BAR_6_SLOT_0       = 69;
SET @ACTION_BAR_6_SLOT_MINUS   = 70;
SET @ACTION_BAR_6_SLOT_EQUALS  = 71;

SET @ACTION_BAR_7_SLOT_1       = 72;
SET @ACTION_BAR_7_SLOT_2       = 73;
SET @ACTION_BAR_7_SLOT_3       = 74;
SET @ACTION_BAR_7_SLOT_4       = 75;
SET @ACTION_BAR_7_SLOT_5       = 76;
SET @ACTION_BAR_7_SLOT_6       = 77;
SET @ACTION_BAR_7_SLOT_7       = 78;
SET @ACTION_BAR_7_SLOT_8       = 79;
SET @ACTION_BAR_7_SLOT_9       = 80;
SET @ACTION_BAR_7_SLOT_0       = 81;
SET @ACTION_BAR_7_SLOT_MINUS   = 82;
SET @ACTION_BAR_7_SLOT_EQUALS  = 83;

SET @ACTION_BAR_8_SLOT_1       = 84;
SET @ACTION_BAR_8_SLOT_2       = 85;
SET @ACTION_BAR_8_SLOT_3       = 86;
SET @ACTION_BAR_8_SLOT_4       = 87;
SET @ACTION_BAR_8_SLOT_5       = 88;
SET @ACTION_BAR_8_SLOT_6       = 89;
SET @ACTION_BAR_8_SLOT_7       = 90;
SET @ACTION_BAR_8_SLOT_8       = 91;
SET @ACTION_BAR_8_SLOT_9       = 92;
SET @ACTION_BAR_8_SLOT_0       = 93;
SET @ACTION_BAR_8_SLOT_MINUS   = 94;
SET @ACTION_BAR_8_SLOT_EQUALS  = 95;