################################
# Languages.db2 (10.0.5.48317) #
################################

SET @LANG_UNIVERSAL          = 0;
SET @LANG_ORCISH             = 1;
SET @LANG_DARNASSIAN         = 2;
SET @LANG_TAURAHE            = 3;
SET @LANG_DWARVISH           = 6;
SET @LANG_COMMON             = 7;
SET @LANG_DEMONIC            = 8;
SET @LANG_TITAN              = 9;
SET @LANG_THALASSIAN         = 10;
SET @LANG_DRACONIC           = 11;
SET @LANG_KALIMAG            = 12;
SET @LANG_GNOMISH            = 13;
SET @LANG_TROLL              = 14;
SET @LANG_GUTTERSPEAK        = 33;
SET @LANG_DRAENEI            = 35;
SET @LANG_ZOMBIE             = 36;
SET @LANG_GNOMISH_BINARY     = 37;
SET @LANG_GOBLIN_BINARY      = 38;
SET @LANG_WORGEN             = 39;
SET @LANG_GOBLIN             = 40;
SET @LANG_PANDAREN_NEUTRAL   = 42;
SET @LANG_PANDAREN_ALLIANCE  = 43;
SET @LANG_PANDAREN_HORDE     = 44;
SET @LANG_SPRITE             = 168;
SET @LANG_SHATH_YAR          = 178;
SET @LANG_NERGLISH           = 179;
SET @LANG_MOONKIN            = 180;
SET @LANG_SHALASSIAN         = 181;
SET @LANG_THALASSIAN_2       = 182;
SET @LANG_ADDON              = 183;
SET @LANG_ADDON_LOGGED       = 184;
SET @LANG_VULPERA            = 285;
SET @LANG_COMPLEX_CIPHER     = 287;
SET @LANG_BASIC_CYPHER       = 288;
SET @LANG_METRIAL            = 290;
SET @LANG_ALTONIAN           = 291;
SET @LANG_SOPRANIAN          = 292;
SET @LANG_AEALIC             = 293;
SET @LANG_DEALIC             = 294;
SET @LANG_TREBELIM           = 295;
SET @LANG_BASSALIM           = 296;
SET @LANG_EMBEDDED_LANGUAGES = 297;
SET @LANG_UNKNOWABLE         = 298;