#################
# Smart Scripts #
#################

# Object type (creature, gameobject, quest, etc.)
SET @SMART_TYPE_CREATURE                             =     0; # creature_template.entry or creature.guid
SET @SMART_TYPE_GAMEOBJECT                           =     1; # gameobject_template.entry or gameobject.guid
SET @SMART_TYPE_AREATRIGGER                          =     2; # Areatrigger.db2 (ID)
SET @SMART_TYPE_EVENT                                =     3; #
SET @SMART_TYPE_GOSSIP                               =     4; #
SET @SMART_TYPE_QUEST                                =     5; # quest_template.ID
SET @SMART_TYPE_SPELL                                =     6; #
SET @SMART_TYPE_TRANSPORT                            =     7; #
SET @SMART_TYPE_INSTANCE                             =     8; #
SET @SMART_TYPE_TIMED_ACTIONLIST                     =     9; # smart_scripts.entryorguid
SET @SMART_TYPE_SCENE                                =    10; # scene_template.id
SET @SMART_TYPE_AREATRIGGER_ENTITY                   =    11; # areatrigger_template.Id (IsServerSide = 0)
SET @SMART_TYPE_AREATRIGGER_ENTITY_SERVERSIDE        =    12; # areatrigger_template.Id (IsServerSide = 1)

# Event Types
SET @SMART_EVENT_UPDATE_IC                           =     0; # In combat (PARAM1 InitialMin PARAM2 InitialMax PARAM3 RepeatMin PARAM4 RepeatMax)
SET @SMART_EVENT_UPDATE_OOC                          =     1; # Out of combat (PARAM1 InitialMin PARAM2 InitialMax PARAM3 RepeatMin PARAM4 RepeatMax)
SET @SMART_EVENT_HEALTH_PCT                          =     2; # Health percentage (PARAM1 MinHpPct PARAM2 MaxHpPct PARAM3 RepeatMin PARAM4 RepeatMax)
SET @SMART_EVENT_MANA_PCT                            =     3; # Mana percentage (PARAM1 MinManaPct PARAM2 MaxManaPct PARAM3 RepeatMin PARAM4 RepeatMax)
SET @SMART_EVENT_AGGRO                               =     4; # On creature aggro
SET @SMART_EVENT_KILL                                =     5; # On creature kill (PARAM1 CooldownMin PARAM2 CooldownMax PARAM3 Player only (0/1) PARAM4 creature_template.entry  (If Param3 is 0))
SET @SMART_EVENT_DEATH                               =     6; # On creature death
SET @SMART_EVENT_EVADE                               =     7; # On creature evade attack
SET @SMART_EVENT_SPELLHIT                            =     8; # On spell hit (PARAM1 SpellID PARAM2 School PARAM3 CooldownMin PARAM4 CooldownMax)
SET @SMART_EVENT_RANGE                               =     9; # On target in range (PARAM1 MinDist PARAM2 MaxDist PARAM3 RepeatMin PARAM4 RepeatMax)
SET @SMART_EVENT_OOC_LOS                             =    10; # On target in range (Out of combat) (PARAM1 HostilityMode: 0 → Hostile 1 → NotHostile 2 → Any PARAM2 MaxRange PARAM3 CooldownMin PARAM4 CooldownMax PARAM5 Player only (0/1))
SET @SMART_EVENT_RESPAWN                             =    11; # On spawn/respawn (PARAM1 Type: 0 → None 1 → Map 2 → Area PARAM2 MapId PARAM3 ZoneId)
SET @SMART_EVENT_TARGET_HEALTH_PCT                   =    12; # UNUSED, DO NOT REUSE
SET @SMART_EVENT_VICTIM_CASTING                      =    13; # On target casting spell (PARAM1 RepeatMin PARAM2 RepeatMax PARAM3 SpellID (0 any))
SET @SMART_EVENT_FRIENDLY_HEALTH                     =    14; # UNUSED, DO NOT REUSE
SET @SMART_EVENT_FRIENDLY_IS_CC                      =    15; # On friendly in cc (PARAM1 Radius PARAM2 RepeatMin PARAM3 RepeatMax)
SET @SMART_EVENT_FRIENDLY_MISSING_BUFF               =    16; # On friendly lost buff (PARAM1 SpellID PARAM2 Radius PARAM3 RepeatMin PARAM4 RepeatMax)
SET @SMART_EVENT_SUMMONED_UNIT                       =    17; # On summoned unit (PARAM1 creature_template.entry (0 any) PARAM2 CooldownMin PARAM3 CooldownMax)
SET @SMART_EVENT_TARGET_MANA_PCT                     =    18; # UNUSED, DO NOT REUSE
SET @SMART_EVENT_ACCEPTED_QUEST                      =    19; # On target accepted quest (PARAM1 QuestID (0 any) PARAM2 RepeatMin PARAM3 RepeatMax)
SET @SMART_EVENT_REWARD_QUEST                        =    20; # On target rewarded quest (PARAM1 QuestID (0 any) PARAM2 RepeatMin PARAM3 RepeatMax)
SET @SMART_EVENT_REACHED_HOME                        =    21; # On creature reached home
SET @SMART_EVENT_RECEIVE_EMOTE                       =    22; # On emote received (PARAM1 EmoteID (Emotes.db2) PARAM2 CooldownMin PARAM3 CooldownMax)
SET @SMART_EVENT_HAS_AURA                            =    23; # On creature has aura (PARAM1 SpellID PARAM2 Stacks PARAM3 RepeatMin PARAM4 RepeatMax)
SET @SMART_EVENT_TARGET_BUFFED                       =    24; # On target buffed with spell (PARAM1 SpellID PARAM2 Stacks PARAM3 RepeatMin PARAM4 RepeatMax)
SET @SMART_EVENT_RESET                               =    25; # After combat or on spawn/respawn
SET @SMART_EVENT_IC_LOS                              =    26; # On target in range (In combat) (PARAM1 HostilityMode: 0 → Hostile 1 → NotHostile 2 → Any PARAM2 MaxRange PARAM3 CooldownMin PARAM4 CooldownMax PARAM5 Player only (0/1))
SET @SMART_EVENT_PASSENGER_BOARDED                   =    27; # On passenger boarded (PARAM1 CooldownMin PARAM2 CooldownMax)
SET @SMART_EVENT_PASSENGER_REMOVED                   =    28; # On passenger removed (PARAM1 CooldownMin PARAM2 CooldownMax)
SET @SMART_EVENT_CHARMED                             =    29; # On creature charmed (PARAM1 Event: 0 → On apply 1 → On remove)
SET @SMART_EVENT_CHARMED_TARGET                      =    30; # UNUSED, DO NOT REUSE
SET @SMART_EVENT_SPELLHIT_TARGET                     =    31; # On target spell hit (PARAM1 SpellID PARAM2 School PARAM3 RepeatMin PARAM4 RepeatMax)
SET @SMART_EVENT_DAMAGED                             =    32; # On damaged (PARAM1 MinDmg PARAM2 MaxDmg PARAM3 RepeatMin PARAM4 RepeatMax)
SET @SMART_EVENT_DAMAGED_TARGET                      =    33; # On target damaged (PARAM1 MinDmg PARAM2 MaxDmg PARAM3 RepeatMin PARAM4 RepeatMax)
SET @SMART_EVENT_MOVEMENTINFORM                      =    34; # On movement inform (PARAM1 MovementType : 0 → Any 1 → Random 2 → Waypoint ( waypoint_data.point ) 8 → Point 16 → Effect (Jump) PARAM2 PointID (0xFFFFFFFF any))
SET @SMART_EVENT_SUMMON_DESPAWNED                    =    35; # On summoned unit despawned (PARAM1 creature_template.entry PARAM2 CooldownMin PARAM3 CooldownMax)
SET @SMART_EVENT_CORPSE_REMOVED                      =    36; # On creature corpse removed
SET @SMART_EVENT_AI_INIT                             =    37; # On AI init
SET @SMART_EVENT_DATA_SET                            =    38; # On data set (See SMART_ACTION_SET_DATA) (PARAM1 Field PARAM2 Value PARAM3 CooldownMin PARAM4 CooldownMax)
SET @SMART_EVENT_WAYPOINT_START                      =    39; # UNUSED, DO NOT REUSE
SET @SMART_EVENT_WAYPOINT_REACHED                    =    40; # On creature waypoint ID reached (PARAM1 PointID (0 any) PARAM2 PathID (0 any))
SET @SMART_EVENT_TRANSPORT_ADDPLAYER                 =    41; # Not yet implemented
SET @SMART_EVENT_TRANSPORT_ADDCREATURE               =    42; # Not yet implemented (PARAM1 Entry (0 any))
SET @SMART_EVENT_TRANSPORT_REMOVE_PLAYER             =    43; # Not yet implemented
SET @SMART_EVENT_TRANSPORT_RELOCATE                  =    44; # Not yet implemented (PARAM1 PointID)
SET @SMART_EVENT_INSTANCE_PLAYER_ENTER               =    45; # Not yet implemented (PARAM1 Team (0 any) PARAM2 CooldownMin PARAM3 CooldownMax)
SET @SMART_EVENT_AREATRIGGER_ONTRIGGER               =    46; # On areatrigger triggered (PARAM1 TriggerId (0 any))
SET @SMART_EVENT_QUEST_ACCEPTED                      =    47; # On target quest accepted
SET @SMART_EVENT_QUEST_OBJ_COMPLETION                =    48; # On target quest objective completed (PARAM1 quest_objectives.ID)
SET @SMART_EVENT_QUEST_COMPLETION                    =    49; # On target quest completed
SET @SMART_EVENT_QUEST_REWARDED                      =    50; # On target quest rewarded
SET @SMART_EVENT_QUEST_FAIL                          =    51; # On target quest failed
SET @SMART_EVENT_TEXT_OVER                           =    52; # On text over event triggered after SMART_ACTION_TALK (PARAM1 creature_text.GroupID PARAM2 creature_text.CreatureID (0 any))
SET @SMART_EVENT_RECEIVE_HEAL                        =    53; # On creature received healing (PARAM1 MinHeal PARAM2 MaxHeal PARAM3 CooldownMin PARAM4 CooldownMax)
SET @SMART_EVENT_JUST_SUMMONED                       =    54; # On summon
SET @SMART_EVENT_WAYPOINT_PAUSED                     =    55; # On creature waypoint ID paused (PARAM1 PointID (0 any) PARAM2 PathID (0 any))
SET @SMART_EVENT_WAYPOINT_RESUMED                    =    56; # On creature waypoint ID resumed (PARAM1 PointID (0 any) PARAM2 PathID (0 any))
SET @SMART_EVENT_WAYPOINT_STOPPED                    =    57; # On creature waypoint ID stopped (PARAM1 PointID (0 any) PARAM2 PathID (0 any))
SET @SMART_EVENT_WAYPOINT_ENDED                      =    58; # On creature waypoint ID ended (PARAM1 PointID (0 any) PARAM2 PathID (0 any))
SET @SMART_EVENT_TIMED_EVENT_TRIGGERED               =    59; # On timed event triggered  (See SMART_ACTION_TRIGGER_TIMED_EVENT) (PARAM1 Id)
SET @SMART_EVENT_UPDATE                              =    60; # On event update (PARAM1 InitialMin PARAM2 InitialMax PARAM3 RepeatMin PARAM4 RepeatMax)
SET @SMART_EVENT_LINK                                =    61; # Used to link together multiple events ( smart_scripts.link )
SET @SMART_EVENT_GOSSIP_SELECT                       =    62; # On gossip option selected (PARAM1 gossip_menu_option.MenuID PARAM2 gossip_menu_option.OptionID)
SET @SMART_EVENT_JUST_CREATED                        =    63; # On spawn/summon
SET @SMART_EVENT_GOSSIP_HELLO                        =    64; # On gossip hello (PARAM1 NoReportUse (for GOs): 0 → On gossip hello and on report use  (Action could be executed twice) 1 → On gossip hello 2 → On report use)
SET @SMART_EVENT_FOLLOW_COMPLETED                    =    65; # On follow completed
SET @SMART_EVENT_EVENT_PHASE_CHANGE                  =    66; # UNUSED, DO NOT REUSE
SET @SMART_EVENT_IS_BEHIND_TARGET                    =    67; # UNUSED, DO NOT REUSE
SET @SMART_EVENT_GAME_EVENT_START                    =    68; # On game_event started (PARAM1 game_event.eventEntry)
SET @SMART_EVENT_GAME_EVENT_END                      =    69; # On game_event ended (PARAM1 game_event.eventEntry)
SET @SMART_EVENT_GO_LOOT_STATE_CHANGED               =    70; # On go state changed (PARAM1 State: 0 → Not Ready 1 → Ready 2 → Activated 3 → Just deactivated)
SET @SMART_EVENT_GO_EVENT_INFORM                     =    71; # On go event inform (PARAM1 EventId)
SET @SMART_EVENT_ACTION_DONE                         =    72; # On action done (See SMART_ACTION_DO_ACTION) (PARAM1 ActionId)
SET @SMART_EVENT_ON_SPELLCLICK                       =    73; # On spellclick
SET @SMART_EVENT_FRIENDLY_HEALTH_PCT                 =    74; # On friendly health percentage (PARAM1 MinHpPct PARAM2 MaxHpPct PARAM3 RepeatMin PARAM4 RepeatMax PARAM5 Radius)
SET @SMART_EVENT_DISTANCE_CREATURE                   =    75; # On creature guid/entry is within distance (PARAM1 creature.guid PARAM2 creature_template.entry PARAM3 Distance PARAM4 Repeat interval (ms))
SET @SMART_EVENT_DISTANCE_GAMEOBJECT                 =    76; # On gameobject guid/entry is within distance (PARAM1 gameobject.guid PARAM2 gameobject_template.entry PARAM3 Distance PARAM4 Repeat interval (ms))
SET @SMART_EVENT_COUNTER_SET                         =    77; # On CounterID value equal to a specified value  (See SMART_ACTION_SET_COUNTER) (PARAM1 CounterID PARAM2 Value PARAM3 CooldownMin PARAM4 CooldownMax)
SET @SMART_EVENT_SCENE_START                         =    78; # On scene start
SET @SMART_EVENT_SCENE_TRIGGER                       =    79; # On scene trigger
SET @SMART_EVENT_SCENE_CANCEL                        =    80; # On scene cancel
SET @SMART_EVENT_SCENE_COMPLETE                      =    81; # On scene complete
SET @SMART_EVENT_SUMMONED_UNIT_DIES                  =    82; # On summoned unit dies
SET @SMART_EVENT_ON_SPELL_CAST                       =    83; # On spell cast (PARAM1 SpellID PARAM2 CooldownMin PARAM3 CooldownMax)
SET @SMART_EVENT_ON_SPELL_FAILED                     =    84; # On spell failed (PARAM1 SpellID PARAM2 CooldownMin PARAM3 CooldownMax)
SET @SMART_EVENT_ON_SPELL_START                      =    85; # On spell start (PARAM1 SpellID PARAM2 CooldownMin PARAM3 CooldownMax)
SET @SMART_EVENT_ON_DESPAWN                          =    86; # On despawn

# Event Phase Mask
# Event can only occur if the source is in this event phase. The default event phase is SMART_EVENT_PHASE_ALWAYS
SET @SMART_EVENT_PHASE_ALWAYS                        =    0; # 0x000 - Means all phases (1..12)
SET @SMART_EVENT_PHASE_1                             =    1; # 0x001 - Phase  1 only
SET @SMART_EVENT_PHASE_2                             =    2; # 0x002 - Phase  2 only
SET @SMART_EVENT_PHASE_3                             =    4; # 0x004 - Phase  3 only
SET @SMART_EVENT_PHASE_4                             =    8; # 0x008 - Phase  4 only
SET @SMART_EVENT_PHASE_5                             =   16; # 0x010 - Phase  5 only
SET @SMART_EVENT_PHASE_6                             =   32; # 0x020 - Phase  6 only
SET @SMART_EVENT_PHASE_7                             =   64; # 0x040 - Phase  7 only
SET @SMART_EVENT_PHASE_8                             =  128; # 0x080 - Phase  8 only
SET @SMART_EVENT_PHASE_9                             =  256; # 0x100 - Phase  9 only
SET @SMART_EVENT_PHASE_10                            =  512; # 0x200 - Phase 10 only
SET @SMART_EVENT_PHASE_11                            = 1024; # 0x400 - Phase 11 only
SET @SMART_EVENT_PHASE_12                            = 2048; # 0x800 - Phase 12 only

# Event Flags
SET @SMART_EVENT_FLAG_NO_FLAG                        =    0; # 0x000
SET @SMART_EVENT_FLAG_NOT_REPEATABLE                 =    1; # 0x001 - Event can not repeat
SET @SMART_EVENT_FLAG_DIFFICULTY_0                   =    2; # 0x002 - Event only occurs in instance difficulty 0
SET @SMART_EVENT_FLAG_DIFFICULTY_1                   =    4; # 0x004 - Event only occurs in instance difficulty 1
SET @SMART_EVENT_FLAG_DIFFICULTY_2                   =    8; # 0x008 - Event only occurs in instance difficulty 2
SET @SMART_EVENT_FLAG_DIFFICULTY_3                   =   16; # 0x010 - Event only occurs in instance difficulty 3
SET @SMART_EVENT_FLAG_RESERVED_5                     =   32; # 0x020
SET @SMART_EVENT_FLAG_RESERVED_6                     =   64; # 0x040
SET @SMART_EVENT_FLAG_DEBUG_ONLY                     =  128; # 0x080 - Event only occurs in debug build
SET @SMART_EVENT_FLAG_DONT_RESET                     =  256; # 0x100 - Event will not reset in SmartScript::OnReset()
SET @SMART_EVENT_FLAG_WHILE_CHARMED                  =  512; # 0x200 - Event occurs even if AI owner is charmed
SET @SMART_EVENT_FLAG_DIFFICULTY_ALL                 = @SMART_EVENT_FLAG_DIFFICULTY_0 + @SMART_EVENT_FLAG_DIFFICULTY_1 + @SMART_EVENT_FLAG_DIFFICULTY_2 + @SMART_EVENT_FLAG_DIFFICULTY_3;
SET @SMART_EVENT_FLAGS_ALL                           = @SMART_EVENT_FLAG_NOT_REPEATABLE + @SMART_EVENT_FLAG_DIFFICULTY_ALL + @SMART_EVENT_FLAG_RESERVED_5 + @SMART_EVENT_FLAG_RESERVED_6 + @SMART_EVENT_FLAG_DEBUG_ONLY + @SMART_EVENT_FLAG_DONT_RESET + @SMART_EVENT_FLAG_WHILE_CHARMED;

# Action Types
SET @SMART_ACTION_NONE                               =     0; # No action
SET @SMART_ACTION_TALK                               =     1; # groupID from creature_text, duration to wait before TEXT_OVER event is triggered, useTalkTarget (0/1) - use target as talk target
SET @SMART_ACTION_TALK_PARAM1_GROUPID                =     0;
SET @SMART_ACTION_TALK_PARAM2_DURATION_TEXT_OVER     =     0;
SET @SMART_ACTION_TALK_PARAM3_USE_TALK_TARGET        =     0;
SET @SMART_ACTION_SET_FACTION                        =     2; # FactionId (or 0 for default)
SET @SMART_ACTION_MORPH_TO_ENTRY_OR_MODEL            =     3; # Creature_template entry(param1) OR ModelId (param2) (or 0 for both to demorph)
SET @SMART_ACTION_SOUND                              =     4; # SoundId, onlySelf
SET @SMART_ACTION_PLAY_EMOTE                         =     5; # EmoteId
SET @SMART_ACTION_FAIL_QUEST                         =     6; # QuestID
SET @SMART_ACTION_OFFER_QUEST                        =     7; # QuestID, directAdd
SET @SMART_ACTION_SET_REACT_STATE                    =     8; # state
SET @SMART_ACTION_ACTIVATE_GOBJECT                   =     9; #
SET @SMART_ACTION_RANDOM_EMOTE                       =    10; # EmoteId1, EmoteId2, EmoteId3...
SET @SMART_ACTION_CAST                               =    11; # SpellId, CastFlags, TriggeredFlags
SET @SMART_ACTION_SUMMON_CREATURE                    =    12; # CreatureID, summonType, duration in ms, attackInvoker, flags(SmartActionSummonCreatureFlags)
SET @SMART_ACTION_THREAT_SINGLE_PCT                  =    13; # Threat%
SET @SMART_ACTION_THREAT_ALL_PCT                     =    14; # Threat%
SET @SMART_ACTION_CALL_AREAEXPLOREDOREVENTHAPPENS    =    15; # QuestID
SET @SMART_ACTION_SET_INGAME_PHASE_GROUP             =    16; # phaseGroupId, apply
SET @SMART_ACTION_SET_EMOTE_STATE                    =    17; # emoteID
SET @SMART_ACTION_SET_UNIT_FLAG                      =    18; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_REMOVE_UNIT_FLAG                   =    19; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_AUTO_ATTACK                        =    20; # AllowAttackState (0 = stop attack, anything else means continue attacking)
SET @SMART_ACTION_ALLOW_COMBAT_MOVEMENT              =    21; # AllowCombatMovement (0 = stop combat based movement, anything else continue attacking)
SET @SMART_ACTION_SET_EVENT_PHASE                    =    22; # Phase
SET @SMART_ACTION_INC_EVENT_PHASE                    =    23; # Value (may be negative to decrement phase, should not be 0)
SET @SMART_ACTION_EVADE                              =    24; # toRespawnPosition (0 = Move to RespawnPosition, 1 = Move to last stored home position)
SET @SMART_ACTION_FLEE_FOR_ASSIST                    =    25; # With Emote
SET @SMART_ACTION_CALL_GROUPEVENTHAPPENS             =    26; # QuestID
SET @SMART_ACTION_COMBAT_STOP                        =    27; #
SET @SMART_ACTION_REMOVEAURASFROMSPELL               =    28; # Spellid (0 removes all auras), charges (0 removes aura)
SET @SMART_ACTION_FOLLOW                             =    29; # Distance (0 = default), Angle (0 = default), EndCreatureEntry, credit, creditType (0monsterkill, 1event)
SET @SMART_ACTION_RANDOM_PHASE                       =    30; # PhaseId1, PhaseId2, PhaseId3...
SET @SMART_ACTION_RANDOM_PHASE_RANGE                 =    31; # PhaseMin, PhaseMax
SET @SMART_ACTION_RESET_GOBJECT                      =    32; #
SET @SMART_ACTION_CALL_KILLEDMONSTER                 =    33; # CreatureId,
SET @SMART_ACTION_SET_INST_DATA                      =    34; # Field, Data, Type (0 = SetData, 1 = SetBossState)
SET @SMART_ACTION_SET_INST_DATA64                    =    35; # Field,
SET @SMART_ACTION_UPDATE_TEMPLATE                    =    36; # Entry
SET @SMART_ACTION_DIE                                =    37; # No Params
SET @SMART_ACTION_SET_IN_COMBAT_WITH_ZONE            =    38; # No Params
SET @SMART_ACTION_CALL_FOR_HELP                      =    39; # Radius, With Emote
SET @SMART_ACTION_SET_SHEATH                         =    40; # Sheath (0-unarmed, 1-melee, 2-ranged)
SET @SMART_ACTION_FORCE_DESPAWN                      =    41; # timer
SET @SMART_ACTION_SET_INVINCIBILITY_HP_LEVEL         =    42; # MinHpValue(+pct, -flat)
SET @SMART_ACTION_MOUNT_TO_ENTRY_OR_MODEL            =    43; # Creature_template entry(param1) OR ModelId (param2) (or 0 for both to dismount)
SET @SMART_ACTION_SET_INGAME_PHASE_ID                =    44; # PhaseId, apply
SET @SMART_ACTION_SET_DATA                           =    45; # Field, Data (only creature @todo)
SET @SMART_ACTION_ATTACK_STOP                        =    46; #
SET @SMART_ACTION_SET_VISIBILITY                     =    47; # on/off
SET @SMART_ACTION_SET_ACTIVE                         =    48; # on/off
SET @SMART_ACTION_ATTACK_START                       =    49; #
SET @SMART_ACTION_SUMMON_GO                          =    50; # GameObjectID, DespawnTime in s
SET @SMART_ACTION_KILL_UNIT                          =    51; #
SET @SMART_ACTION_ACTIVATE_TAXI                      =    52; # TaxiID
SET @SMART_ACTION_WP_START                           =    53; # run/walk (unused / overridden by waypoint_data table move_type column) , pathID, canRepeat, quest, despawntime
SET @SMART_ACTION_WP_PAUSE                           =    54; # time
SET @SMART_ACTION_WP_STOP                            =    55; # despawnTime, quest, fail?
SET @SMART_ACTION_ADD_ITEM                           =    56; # itemID, count
SET @SMART_ACTION_REMOVE_ITEM                        =    57; # itemID, count
SET @SMART_ACTION_INSTALL_AI_TEMPLATE                =    58; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_SET_RUN                            =    59; # 0/1
SET @SMART_ACTION_SET_DISABLE_GRAVITY                =    60; # 0/1
SET @SMART_ACTION_SET_SWIM                           =    61; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_TELEPORT                           =    62; # mapID,
SET @SMART_ACTION_SET_COUNTER                        =    63; # id, value, reset (0/1)
SET @SMART_ACTION_STORE_TARGET_LIST                  =    64; # varID,
SET @SMART_ACTION_WP_RESUME                          =    65; # none
SET @SMART_ACTION_SET_ORIENTATION                    =    66; #
SET @SMART_ACTION_CREATE_TIMED_EVENT                 =    67; # id, InitialMin, InitialMax, RepeatMin(only if it repeats), RepeatMax(only if it repeats), chance
SET @SMART_ACTION_PLAYMOVIE                          =    68; # entry
SET @SMART_ACTION_MOVE_TO_POS                        =    69; # PointId, transport, disablePathfinding, ContactDistance
SET @SMART_ACTION_ENABLE_TEMP_GOBJ                   =    70; # despawnTimer (sec)
SET @SMART_ACTION_EQUIP                              =    71; # entry, slotmask slot1, slot2, slot3 , only slots with mask set will be sent to client, bits are 1, 2, 4, leaving mask 0 is defaulted to mask 7 (send all), slots1-3 are only used if no entry is set
SET @SMART_ACTION_CLOSE_GOSSIP                       =    72; # none
SET @SMART_ACTION_TRIGGER_TIMED_EVENT                =    73; # id(>1)
SET @SMART_ACTION_REMOVE_TIMED_EVENT                 =    74; # id(>1)
SET @SMART_ACTION_ADD_AURA                           =    75; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_OVERRIDE_SCRIPT_BASE_OBJECT        =    76; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_RESET_SCRIPT_BASE_OBJECT           =    77; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_CALL_SCRIPT_RESET                  =    78; # none
SET @SMART_ACTION_SET_RANGED_MOVEMENT                =    79; # Distance, angle
SET @SMART_ACTION_CALL_TIMED_ACTIONLIST              =    80; # ID (overwrites already running actionlist), stop after combat?(0/1), timer update type(0-OOC, 1-IC, 2-ALWAYS)
SET @SMART_ACTION_SET_NPC_FLAG                       =    81; # Flags
SET @SMART_ACTION_ADD_NPC_FLAG                       =    82; # Flags
SET @SMART_ACTION_REMOVE_NPC_FLAG                    =    83; # Flags
SET @SMART_ACTION_SIMPLE_TALK                        =    84; # groupID, can be used to make players say groupID, Text_over event is not triggered, whisper can not be used (Target units will say the text)
SET @SMART_ACTION_SELF_CAST                          =    85; # spellID, castFlags
SET @SMART_ACTION_CROSS_CAST                         =    86; # spellID, castFlags, CasterTargetType, CasterTarget param1, CasterTarget param2, CasterTarget param3, ( + the original target fields as Destination target), CasterTargets will cast spellID on all Targets (use with caution if targeting multiple * multiple units)
SET @SMART_ACTION_CALL_RANDOM_TIMED_ACTIONLIST       =    87; # script9 ids 1-9
SET @SMART_ACTION_CALL_RANDOM_RANGE_TIMED_ACTIONLIST =    88; # script9 id min, max
SET @SMART_ACTION_RANDOM_MOVE                        =    89; # maxDist
SET @SMART_ACTION_SET_UNIT_FIELD_BYTES_1             =    90; # bytes, target
SET @SMART_ACTION_REMOVE_UNIT_FIELD_BYTES_1          =    91; # bytes, target
SET @SMART_ACTION_INTERRUPT_SPELL                    =    92;
SET @SMART_ACTION_SEND_GO_CUSTOM_ANIM                =    93; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_SET_DYNAMIC_FLAG                   =    94; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_ADD_DYNAMIC_FLAG                   =    95; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_REMOVE_DYNAMIC_FLAG                =    96; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_JUMP_TO_POS                        =    97; # SpeedXY, SpeedZ, Gravity, UseDefaultGravity, PointId, ContactDistance
SET @SMART_ACTION_SEND_GOSSIP_MENU                   =    98; # menuId, optionId
SET @SMART_ACTION_GO_SET_LOOT_STATE                  =    99; # state
SET @SMART_ACTION_SEND_TARGET_TO_TARGET              =   100; # id
SET @SMART_ACTION_SET_HOME_POS                       =   101; # none
SET @SMART_ACTION_SET_HEALTH_REGEN                   =   102; # 0/1
SET @SMART_ACTION_SET_ROOT                           =   103; # off/on
SET @SMART_ACTION_SET_GO_FLAG                        =   104; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_ADD_GO_FLAG                        =   105; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_REMOVE_GO_FLAG                     =   106; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_SUMMON_CREATURE_GROUP              =   107; # Group, attackInvoker
SET @SMART_ACTION_SET_POWER                          =   108; # PowerType, newPower
SET @SMART_ACTION_ADD_POWER                          =   109; # PowerType, newPower
SET @SMART_ACTION_REMOVE_POWER                       =   110; # PowerType, newPower
SET @SMART_ACTION_GAME_EVENT_STOP                    =   111; # GameEventId
SET @SMART_ACTION_GAME_EVENT_START                   =   112; # GameEventId
SET @SMART_ACTION_START_CLOSEST_WAYPOINT             =   113; # wp1, wp2, wp3, wp4, wp5, wp6, wp7
SET @SMART_ACTION_MOVE_OFFSET                        =   114; # PointId
SET @SMART_ACTION_RANDOM_SOUND                       =   115; # soundId1, soundId2, soundId3, soundId4, soundId5, onlySelf
SET @SMART_ACTION_SET_CORPSE_DELAY                   =   116; # timer
SET @SMART_ACTION_DISABLE_EVADE                      =   117; # 0/1 (1 = disabled, 0 = enabled)
SET @SMART_ACTION_GO_SET_GO_STATE                    =   118; # state
SET @SMART_ACTION_SET_CAN_FLY                        =   119; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_REMOVE_AURAS_BY_TYPE               =   120; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_SET_SIGHT_DIST                     =   121; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_FLEE                               =   122; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_ADD_THREAT                         =   123; # +threat, -threat
SET @SMART_ACTION_LOAD_EQUIPMENT                     =   124; # id
SET @SMART_ACTION_TRIGGER_RANDOM_TIMED_EVENT         =   125; # id min range, id max range
SET @SMART_ACTION_REMOVE_ALL_GAMEOBJECTS             =   126; # UNUSED, DO NOT REUSE
SET @SMART_ACTION_PAUSE_MOVEMENT                     =   127; # MovementSlot (default = 0, active = 1, controlled = 2), PauseTime (ms), Force
SET @SMART_ACTION_PLAY_ANIMKIT                       =   128; # id, type (0 = oneShot, 1 = aiAnim, 2 = meleeAnim, 3 = movementAnim)
SET @SMART_ACTION_SCENE_PLAY                         =   129; # sceneId
SET @SMART_ACTION_SCENE_CANCEL                       =   130; # sceneId
SET @SMART_ACTION_SPAWN_SPAWNGROUP                   =   131; # Group ID, min secs, max secs, spawnflags
SET @SMART_ACTION_DESPAWN_SPAWNGROUP                 =   132; # Group ID, min secs, max secs, spawnflags
SET @SMART_ACTION_RESPAWN_BY_SPAWNID                 =   133; # spawnType, spawnId
SET @SMART_ACTION_INVOKER_CAST                       =   134; # spellID, castFlags
SET @SMART_ACTION_PLAY_CINEMATIC                     =   135; # entry, cinematic
SET @SMART_ACTION_SET_MOVEMENT_SPEED                 =   136; # movementType, speedInteger, speedFraction
SET @SMART_ACTION_PLAY_SPELL_VISUAL_KIT              =   137; # spellVisualKitId, kitType (unknown values, copypaste from packet dumps), duration
SET @SMART_ACTION_OVERRIDE_LIGHT                     =   138; # zoneId, overrideLightID, transitionMilliseconds
SET @SMART_ACTION_OVERRIDE_WEATHER                   =   139; # zoneId, weatherId, intensity
SET @SMART_ACTION_SET_AI_ANIM_KIT                    =   140; # DEPRECATED, DO REUSE (it was never used in any branch, treat as free action id)
SET @SMART_ACTION_SET_HOVER                          =   141; # 0/1
SET @SMART_ACTION_SET_HEALTH_PCT                     =   142; # percent
SET @SMART_ACTION_CREATE_CONVERSATION                =   143; # conversation_template.id
SET @SMART_ACTION_SET_IMMUNE_PC                      =   144; # 0/1
SET @SMART_ACTION_SET_IMMUNE_NPC                     =   145; # 0/1
SET @SMART_ACTION_SET_UNINTERACTIBLE                 =   146; # 0/1
SET @SMART_ACTION_ACTIVATE_GAMEOBJECT                =   147; # GameObjectActions
SET @SMART_ACTION_ADD_TO_STORED_TARGET_LIST          =   148; # varID
SET @SMART_ACTION_BECOME_PERSONAL_CLONE_FOR_PLAYER   =   149; # summonType 1-8, duration in ms
SET @SMART_ACTION_TRIGGER_GAME_EVENT                 =   150; # eventId, useSaiTargetAsGameEventSource
SET @SMART_ACTION_DO_ACTION                          =   151; # actionId

# Target Types
SET @SMART_TARGET_NONE                               =     0; # NONE
SET @SMART_TARGET_SELF                               =     1; # Self cast
SET @SMART_TARGET_VICTIM                             =     2; # Our current target (ie: highest aggro)
SET @SMART_TARGET_HOSTILE_SECOND_AGGRO               =     3; # Second highest aggro, maxdist, playerOnly, powerType + 1
SET @SMART_TARGET_HOSTILE_LAST_AGGRO                 =     4; # Dead last on aggro, maxdist, playerOnly, powerType + 1
SET @SMART_TARGET_HOSTILE_RANDOM                     =     5; # Just any random target on our threat list, maxdist, playerOnly, powerType + 1
SET @SMART_TARGET_HOSTILE_RANDOM_NOT_TOP             =     6; # Any random target except top threat, maxdist, playerOnly, powerType + 1
SET @SMART_TARGET_ACTION_INVOKER                     =     7; # Unit who caused this Event to occur
SET @SMART_TARGET_POSITION                           =     8; # use xyz from event params
SET @SMART_TARGET_CREATURE_RANGE                     =     9; # CreatureEntry(0any), minDist, maxDist
SET @SMART_TARGET_CREATURE_GUID                      =    10; # guid, entry
SET @SMART_TARGET_CREATURE_DISTANCE                  =    11; # CreatureEntry(0any), maxDist
SET @SMART_TARGET_STORED                             =    12; # id, uses pre-stored target(list)
SET @SMART_TARGET_GAMEOBJECT_RANGE                   =    13; # entry(0any), min, max
SET @SMART_TARGET_GAMEOBJECT_GUID                    =    14; # guid, entry
SET @SMART_TARGET_GAMEOBJECT_DISTANCE                =    15; # entry(0any), maxDist
SET @SMART_TARGET_INVOKER_PARTY                      =    16; # invoker's party members
SET @SMART_TARGET_PLAYER_RANGE                       =    17; # min, max
SET @SMART_TARGET_PLAYER_DISTANCE                    =    18; # maxDist
SET @SMART_TARGET_CLOSEST_CREATURE                   =    19; # CreatureEntry(0any), maxDist, dead?
SET @SMART_TARGET_CLOSEST_GAMEOBJECT                 =    20; # entry(0any), maxDist
SET @SMART_TARGET_CLOSEST_PLAYER                     =    21; # maxDist
SET @SMART_TARGET_ACTION_INVOKER_VEHICLE             =    22; # Unit's vehicle who caused this Event to occur
SET @SMART_TARGET_OWNER_OR_SUMMONER                  =    23; # Unit's owner or summoner, Use Owner/Charmer of this unit
SET @SMART_TARGET_THREAT_LIST                        =    24; # All units on creature's threat list, maxdist
SET @SMART_TARGET_CLOSEST_ENEMY                      =    25; # maxDist, playerOnly
SET @SMART_TARGET_CLOSEST_FRIENDLY                   =    26; # maxDist, playerOnly
SET @SMART_TARGET_LOOT_RECIPIENTS                    =    27; # all players that have tagged this creature (for kill credit)
SET @SMART_TARGET_FARTHEST                           =    28; # maxDist, playerOnly, isInLos
SET @SMART_TARGET_VEHICLE_PASSENGER                  =    29; # seatMask (0 - all seats)
SET @SMART_TARGET_CLOSEST_UNSPAWNED_GAMEOBJECT       =    30; # entry(0any), maxDist

SET @SMART_CAST_NO_FLAG                              =     0; # 0x00
SET @SMART_CAST_INTERRUPT_PREVIOUS                   =     1; # 0x01 - Interrupt any spell casting
SET @SMART_CAST_TRIGGERED                            =     2; # 0x02 - Triggered (this makes spell cost zero mana and have no cast time)
SET @SMART_CAST_FORCE_CAST                           =     4; # 0x04 - Forces cast even if creature is out of mana or out of range
SET @SMART_CAST_NO_MELEE_IF_OOM                      =     8; # 0x08 - Prevents creature from entering melee if out of mana or out of range
SET @SMART_CAST_FORCE_TARGET_SELF                    =    16; # 0x10 - Forces the target to cast this spell on itself
SET @SMART_CAST_AURA_NOT_PRESENT                     =    32; # 0x20 - Only casts the spell if the target does not have an aura from the spell
SET @SMART_CAST_COMBAT_MOVE                          =    64; # 0x40 - Prevents combat movement if cast successful. Allows movement on range, OOM, LOS

SET @SMART_SPAWN_FLAG_NONE                           =     0; # 0x00
SET @SMART_SPAWN_FLAG_IGNORE_RESPAWN                 =     1; # 0x01
SET @SMART_SPAWN_FLAG_FORCE_SPAWN                    =     2; # 0x02
SET @SMART_SPAWN_FLAG_NOSAVE_RESPAWN                 =     4; # 0x04

SET @SMART_RESPAWN_CONDITION_NONE                    =     0;
SET @SMART_RESPAWN_CONDITION_MAP                     =     1;
SET @SMART_RESPAWN_CONDITION_AREA                    =     2;
SET @SMART_RESPAWN_CONDITION_END                     =     3;