##########
# Spells #
##########

SET @SPELL_GENERIC_ATTACK                     = 88163;
SET @SPELL_WARRIOR_SLAM                       = 1464;
SET @SPELL_HUMAN_RACIAL_WILL_TO_SURVIVE       = 59752;
SET @SPELL_ORC_RACIAL_BLOOD_FURY              = 20572;
SET @SPELL_DWARF_RACIAL_STONEFORM             = 20594;
SET @SPELL_NIGHT_ELF_RACIAL_SHADOWMELD        = 58984;
SET @SPELL_UNDEAD_RIGOR_MORTIS_AURA           = 73523;
SET @SPELL_UNDEAD_RACIAL_WILL_OF_THE_FORSAKEN = 7744;
SET @SPELL_UNDEAD_RACIAL_CANNIBALIZE          = 20577;
SET @SPELL_TAUREN_RACIAL_WAR_STOMP            = 20549;
SET @SPELL_GNOME_RACIAL_ESCAPE_ARTIST         = 20589;
SET @SPELL_TROLL_RACIAL_BERSERKING            = 26297;
SET @SPELL_GOBLIN_RACIAL_ROCKET_JUMP          = 69070;
SET @SPELL_GOBLIN_RACIAL_ROCKET_BARRAGE       = 69041;
SET @SPELL_BLOOD_ELF_RACIAL_ARCANE_TORRENT    = 69179;
SET @SPELL_DRAENEI_RACIAL_GIFT_OF_THE_NAARU   = 28880;
SET @SPELL_PANDAREN_RACIAL_QUAKING_PALM       = 107079;
SET @SPELL_DRACTHYR_LIVING_FLAME              = 361469;
SET @SPELL_DRACTHYR_AZURE_STRIKE              = 362969;
SET @SPELL_DRACTHYR_RACIAL_WING_BUFFET        = 357214;
SET @SPELL_DRACTHYR_RACIAL_TAIL_SWIPE         = 368970;
SET @SPELL_DRACTHYR_RACIAL_GLIDE              = 358733;