##########################
# NPC Stormwind Infantry #
# ENTRY 49869            #
##########################

SOURCE ../../../sql/wowcore/world/0_includes/smart_scripts.sql
SOURCE ../../../sql/wowcore/world/0_includes/languages.sql
SOURCE ../../../sql/wowcore/world/0_includes/emotes.sql
SOURCE ../../../sql/wowcore/world/0_includes/texts.sql

SET @ENTRY         = 49869;
SET @ACTION_LIST   = @ENTRY * 100;
SET @TALK_GROUP_ID = 0;

# Sparring (No proper support in core for neutral factions sparring with each other)
DELETE FROM `creature_template_sparring` WHERE `Entry` = @ENTRY;
INSERT INTO `creature_template_sparring`
(`Entry`, `NoNPCDamageBelowHealthPct`) VALUES
( @ENTRY, 85);

# Sparring Hackfix: Fix position and orientation
UPDATE `creature` SET `position_x` = -8980.947, `position_y` = -67.86479, `position_z` = 89.62673, `orientation` = 0.286907 WHERE `id` = @ENTRY AND `guid` = 280019 LIMIT 1;

# Sparring Hackfix: Add Emote 36 ONESHOT_ATTACK1H
DELETE FROM `creature_addon` WHERE `guid` IN (279888, 279893, 279894, 279906, 279914, 279928, 279945, 279956, 280001, 280002, 280003, 280008, 280018, 280019, 280020);
INSERT INTO `creature_addon`
(`guid`, `path_id`, `mount`, `MountCreatureID`, `StandState`, `AnimTier`, `VisFlags`, `SheathState`, `PvPFlags`,                 `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `visibilityDistanceType`, `auras`) VALUES
(279888,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(279893,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(279894,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(279906,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(279914,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(279928,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(279945,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(279956,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(280001,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(280002,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(280003,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(280008,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(280018,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(280019,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL),
(280020,         0,       0,                 0,            0,          0,          0,             0,          0, @EMOTE_ONESHOT_ATTACK1H,           0,                 0,              0,                        0,    NULL);

# Add missing texts
DELETE FROM `creature_text` WHERE `CreatureID` = @ENTRY AND `GroupID` = @TALK_GROUP_ID;
INSERT INTO `creature_text`
(`CreatureID`,      `GroupID`, `ID`,                                      `Text`,                `Type`,      `Language`, `Probability`,              `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`,        `TextRange`,            `comment`) VALUES
(      @ENTRY, @TALK_GROUP_ID,    0,              'I could use a heal, brother!', @CHAT_MSG_MONSTER_SAY, @LANG_UNIVERSAL,           100, @EMOTE_ONESHOT_SHOUT,          0,       0,               0,             49895, @TEXT_RANGE_NORMAL, 'Stormwind Infantry'),
(      @ENTRY, @TALK_GROUP_ID,    1,                            'I need a heal!', @CHAT_MSG_MONSTER_SAY, @LANG_UNIVERSAL,           100, @EMOTE_ONESHOT_SHOUT,          0,       0,               0,             49898, @TEXT_RANGE_NORMAL, 'Stormwind Infantry'),
(      @ENTRY, @TALK_GROUP_ID,    2, 'Make yourself useful and heal me, Paxton!', @CHAT_MSG_MONSTER_SAY, @LANG_UNIVERSAL,           100, @EMOTE_ONESHOT_SHOUT,          0,       0,               0,             49896, @TEXT_RANGE_NORMAL, 'Stormwind Infantry'),
(      @ENTRY, @TALK_GROUP_ID,    3,                                     'HELP!', @CHAT_MSG_MONSTER_SAY, @LANG_UNIVERSAL,           100, @EMOTE_ONESHOT_SHOUT,          0,       0,               0,             49897, @TEXT_RANGE_NORMAL, 'Stormwind Infantry');

# Enable SmartAI
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = @ENTRY;

# Add more delay between texts
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (-279888, -279893, -279894, -279906, -279914, -279928, -279945, -279956, -280001, -280002, -280003, -280008, -280018, -280019, -280020);
INSERT INTO `smart_scripts`
( `entryorguid`,               `source_type`, `id`, `link`,            `event_type`,             `event_phase_mask`, `event_chance`,             `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`,             `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`,      `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`,                                  `comment`) VALUES
(       -279888,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
# Commented because NPC 951 Brother Paxton is controlling these
#(       -279893,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
#(       -279894,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
#(       -279906,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
#(       -279914,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
(       -279928,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
(       -279945,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
(       -279956,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
(       -280001,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
(       -280002,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
(       -280003,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
(       -280008,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
(       -280018,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
(       -280019,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say'),
(       -280020,        @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             10, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_NONE,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say');

# Used by NPC 951 Brother Paxton
DELETE FROM `smart_scripts` WHERE `entryorguid` = @ACTION_LIST;
INSERT INTO `smart_scripts`
(`entryorguid`,                `source_type`, `id`, `link`,            `event_type`,             `event_phase_mask`, `event_chance`,              `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`,            `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `action_param7`,      `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`,                                  `comment`) VALUES
( @ACTION_LIST, @SMART_TYPE_TIMED_ACTIONLIST,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,              0,              0,              0,              0,              0,                   '', @SMART_ACTION_SIMPLE_TALK,               0,               0,               0,               0,               0,               0,               0, @SMART_TARGET_SELF,               0,               0,               0,               0,          0,          0,          0,          0, 'Stormwind Infantry - Out of Combat - Say');