###############################
# NPC Brother Paxton          #
# ENTRY 951                   #
# GUID  279895                #
#                             #
# Spells:                     #
# 13864 Power Word: Fortitude #
# 93091 Prayer of Healing     #
# 93094 Renew                 #
# 17843 Flash Heal            #
# 69906 Penance (Not Correct) #
###############################

SOURCE ../../../sql/wowcore/world/0_includes/smart_scripts.sql
SOURCE ../../../sql/wowcore/world/0_includes/languages.sql
SOURCE ../../../sql/wowcore/world/0_includes/emotes.sql
SOURCE ../../../sql/wowcore/world/0_includes/spells.sql
SOURCE ../../../sql/wowcore/world/0_includes/texts.sql

SET @ENTRY                          = 951;
SET @GUID                           = 279895;
SET @PATH                           = @GUID * 10;
SET @ACTION_LIST                    = @ENTRY * 100;
SET @TALK_GROUP_ID                  = 0;
SET @ENTRY_STORMWIND_INFANTRY       = 49869;
SET @ACTION_LIST_STORMWIND_INFANTRY = @ENTRY_STORMWIND_INFANTRY * 100;

UPDATE `creature` SET `MovementType` = 2 WHERE `id` = @ENTRY AND`guid` = @GUID;

# Add missing texts
DELETE FROM `creature_text` WHERE `CreatureID` = @ENTRY;
INSERT INTO `creature_text`
(`CreatureID`,      `GroupID`, `ID`,                            `Text`,               `Type`,       `Language`, `Probability`,             `Emote`, `Duration`, `Sound`, `SoundPlayType`, `BroadcastTextId`,        `TextRange`,        `comment`) VALUES
(      @ENTRY, @TALK_GROUP_ID,    0,  'Be healed, $g brother:sister;!', @CHAT_MSG_MONSTER_SAY, @LANG_UNIVERSAL,           100, @EMOTE_ONESHOT_NONE,          0,       0,               0,             49889, @TEXT_RANGE_NORMAL, 'Brother Paxton'), # Penance ?, Prayer of Healing 93091
(      @ENTRY, @TALK_GROUP_ID,    1,    'AND I LAY MY HANDS UPON YOU!', @CHAT_MSG_MONSTER_SAY, @LANG_UNIVERSAL,           100, @EMOTE_ONESHOT_NONE,          0,       0,               0,             49890, @TEXT_RANGE_NORMAL, 'Brother Paxton'), # Prayer of Healing 93091, Renew 93094
(      @ENTRY, @TALK_GROUP_ID,    2, 'Let the Holy Light embrace you!', @CHAT_MSG_MONSTER_SAY, @LANG_UNIVERSAL,           100, @EMOTE_ONESHOT_NONE,          0,       0,               0,             49891, @TEXT_RANGE_NORMAL, 'Brother Paxton'), # Prayer of Healing 93091, Renew 93094
(      @ENTRY, @TALK_GROUP_ID,    3,        'BY THE LIGHT BE RENEWED!', @CHAT_MSG_MONSTER_SAY, @LANG_UNIVERSAL,           100, @EMOTE_ONESHOT_NONE,          0,       0,               0,             49892, @TEXT_RANGE_NORMAL, 'Brother Paxton'), # Prayer of Healing 93091, Renew 93094
(      @ENTRY, @TALK_GROUP_ID,    4,   'FIGHT ON, $G BROTHER:SISTER;!', @CHAT_MSG_MONSTER_SAY, @LANG_UNIVERSAL,           100, @EMOTE_ONESHOT_NONE,          0,       0,               0,             49893, @TEXT_RANGE_NORMAL, 'Brother Paxton'); # Prayer of Healing 93091, Renew 93094

# Path Waypoint Data
DELETE FROM `creature_addon` WHERE `guid` = @GUID;
INSERT INTO `creature_addon`
(`guid`, `path_id`, `mount`, `MountCreatureID`, `StandState`, `AnimTier`, `VisFlags`, `SheathState`, `PvPFlags`, `emote`, `aiAnimKit`, `movementAnimKit`, `meleeAnimKit`, `visibilityDistanceType`, `auras`) VALUES
( @GUID,     @PATH,      0,                  0,            0,          0,          0,             0,          0,       0,           0,                 0,              0,                        0,    NULL);

# Waypoints
DELETE FROM `waypoint_data` WHERE `id` = @PATH;
INSERT INTO `waypoint_data`
( `id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_type`, `action`, `action_chance`, `wpguid`) VALUES
(@PATH,       1,     -8828.11,     -146.515,      80.5553,             0,       0,           0,        0,             100,        0),
(@PATH,       2,     -8824.02,      -150.93,      80.5076,             0,       0,           0,        0,             100,        0),
(@PATH,       3,     -8818.43,      -150.09,      81.4038,             0,       0,           0,        0,             100,        0),
(@PATH,       4,      -8813.2,      -158.87,       81.583,             0,       0,           0,        0,             100,        0),
(@PATH,       5,     -8819.62,      -150.17,      81.1541,             0,       0,           0,        0,             100,        0),
(@PATH,       6,      -8814.2,      -157.29,      81.6671,       2.49744,       0,           0,        0,             100,        0);

# Enable SmartAI
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = @ENTRY;

DELETE FROM `smart_scripts` WHERE `entryorguid` = @ENTRY;
INSERT INTO `smart_scripts`
(    `entryorguid`,                `source_type`, `id`, `link`,            `event_type`,             `event_phase_mask`, `event_chance`,             `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`,                              `action_type`,                 `action_param1`,              `action_param2`,  `action_param3`,  `action_param4`, `action_param5`, `action_param6`, `action_param7`,               `target_type`, `target_param1`,           `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`,                                                                     `comment`) VALUES
(           @ENTRY,         @SMART_TYPE_CREATURE,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,          10000,          10000,              0,              0,              0,                   '',                    @SMART_ACTION_SELF_CAST,     @SPELL_POWER_WORD_FORTITUDE, @SMART_CAST_AURA_NOT_PRESENT,                0,                0,               0,               0,               0,          @SMART_TARGET_SELF,               0,                         0,               0,               0,          0,          0,          0,          0,             'Brother Paxton - OOC - Self Cast Aura \'Power Word: Fortitude\''),
(           @ENTRY,         @SMART_TYPE_CREATURE,    1,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             25, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_CALL_TIMED_ACTIONLIST,                @ACTION_LIST + 0,                            0,                0,                0,               0,               0,               0,          @SMART_TARGET_SELF,               0,                         0,               0,               0,          0,          0,          0,          0,                                                                            ''),
(           @ENTRY,         @SMART_TYPE_CREATURE,    2,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             25, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_CALL_TIMED_ACTIONLIST,                @ACTION_LIST + 1,                            0,                0,                0,               0,               0,               0,          @SMART_TARGET_SELF,               0,                         0,               0,               0,          0,          0,          0,          0,                                                                            ''),
(           @ENTRY,         @SMART_TYPE_CREATURE,    3,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             25, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_CALL_TIMED_ACTIONLIST,                @ACTION_LIST + 2,                            0,                0,                0,               0,               0,               0,          @SMART_TARGET_SELF,               0,                         0,               0,               0,          0,          0,          0,          0,                                                                            ''),
(           @ENTRY,         @SMART_TYPE_CREATURE,    4,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,             25, @SMART_EVENT_FLAG_NO_FLAG,          20000,          30000,          20000,          30000,              0,                   '',        @SMART_ACTION_CALL_TIMED_ACTIONLIST,                @ACTION_LIST + 3,                            0,                0,                0,               0,               0,               0,          @SMART_TARGET_SELF,               0,                         0,               0,               0,          0,          0,          0,          0,                                                                            '');


DELETE FROM `smart_scripts` WHERE `entryorguid` IN (@ACTION_LIST + 0, @ACTION_LIST + 1, @ACTION_LIST + 2, @ACTION_LIST + 3);
INSERT INTO `smart_scripts`
(    `entryorguid`,                `source_type`, `id`, `link`,            `event_type`,             `event_phase_mask`, `event_chance`,             `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`,                              `action_type`,                 `action_param1`,              `action_param2`,  `action_param3`,  `action_param4`, `action_param5`, `action_param6`, `action_param7`,               `target_type`, `target_param1`,           `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`,                                                                     `comment`) VALUES
( @ACTION_LIST + 0, @SMART_TYPE_TIMED_ACTIONLIST,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           8000,           8000,              0,              0,              0,                   '',        @SMART_ACTION_CALL_TIMED_ACTIONLIST, @ACTION_LIST_STORMWIND_INFANTRY,                            0,                0,                0,               0,               0,               0, @SMART_TARGET_CREATURE_GUID,          279906, @ENTRY_STORMWIND_INFANTRY,               0,               0,          0,          0,          0,          0,                    'Brother Paxton - OOC - Trigger Stormwind Infantry Talk 1'),
( @ACTION_LIST + 0, @SMART_TYPE_TIMED_ACTIONLIST,    1,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,              0,              0,              0,              0,              0,                   '',               @SMART_ACTION_PAUSE_MOVEMENT,                               0,                         4000,                0,                0,               0,               0,               0,          @SMART_TARGET_SELF,               0,                         0,               0,               0,          0,          0,          0,          0,                                       'Brother Paxton - OOC - Pause Movement'),
( @ACTION_LIST + 0, @SMART_TYPE_TIMED_ACTIONLIST,    2,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           2000,           2000,              0,              0,              0,                   '',              @SMART_ACTION_SET_ORIENTATION,                               0,                            0,                0,                0,               0,               0,               0, @SMART_TARGET_CREATURE_GUID,          279906, @ENTRY_STORMWIND_INFANTRY,               0,               0,          0,          0,          0,          0,                              'Brother Paxton - OOC - Face Stormwind Infantry'),
( @ACTION_LIST + 0, @SMART_TYPE_TIMED_ACTIONLIST,    3,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           1000,           1000,              0,              0,              0,                   '',                         @SMART_ACTION_TALK,                  @TALK_GROUP_ID,                            0,                1,                0,               0,               0,               0,          @SMART_TARGET_SELF,               0,                         0,               0,               0,          0,          0,          0,          0,                                                'Brother Paxton - OOC - Say 1'),
( @ACTION_LIST + 0, @SMART_TYPE_TIMED_ACTIONLIST,    4,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           2000,           2000,              0,              0,              0,                   '',                         @SMART_ACTION_CAST,        @SPELL_PRAYER_OF_HEALING,                            0,                0,                0,               0,               0,               0, @SMART_TARGET_CREATURE_GUID,          279906, @ENTRY_STORMWIND_INFANTRY,               0,               0,          0,          0,          0,          0,         'Brother Paxton - OOC - Cast Prayer of Healing on Stormwind Infantry'),

( @ACTION_LIST + 1, @SMART_TYPE_TIMED_ACTIONLIST,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           8000,           8000,              0,              0,              0,                   '',        @SMART_ACTION_CALL_TIMED_ACTIONLIST, @ACTION_LIST_STORMWIND_INFANTRY,                            0,                0,                0,               0,               0,               0, @SMART_TARGET_CREATURE_GUID,          279914, @ENTRY_STORMWIND_INFANTRY,               0,               0,          0,          0,          0,          0,                    'Brother Paxton - OOC - Trigger Stormwind Infantry Talk 2'),
( @ACTION_LIST + 1, @SMART_TYPE_TIMED_ACTIONLIST,    1,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,              0,              0,              0,              0,              0,                   '',               @SMART_ACTION_PAUSE_MOVEMENT,                               0,                         4000,                0,                0,               0,               0,               0,          @SMART_TARGET_SELF,               0,                         0,               0,               0,          0,          0,          0,          0,                                       'Brother Paxton - OOC - Pause Movement'),
( @ACTION_LIST + 1, @SMART_TYPE_TIMED_ACTIONLIST,    2,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           2000,           2000,              0,              0,              0,                   '',              @SMART_ACTION_SET_ORIENTATION,                               0,                            0,                0,                0,               0,               0,               0, @SMART_TARGET_CREATURE_GUID,          279914, @ENTRY_STORMWIND_INFANTRY,               0,               0,          0,          0,          0,          0,                              'Brother Paxton - OOC - Face Stormwind Infantry'),
( @ACTION_LIST + 1, @SMART_TYPE_TIMED_ACTIONLIST,    3,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           1000,           1000,              0,              0,              0,                   '',                         @SMART_ACTION_TALK,                  @TALK_GROUP_ID,                            0,                1,                0,               0,               0,               0,          @SMART_TARGET_SELF,               0,                         0,               0,               0,          0,          0,          0,          0,                                                'Brother Paxton - OOC - Say 4'),
( @ACTION_LIST + 1, @SMART_TYPE_TIMED_ACTIONLIST,    4,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           2000,           2000,              0,              0,              0,                   '',                         @SMART_ACTION_CAST,                    @SPELL_RENEW,                            0,                0,                0,               0,               0,               0, @SMART_TARGET_CREATURE_GUID,          279914, @ENTRY_STORMWIND_INFANTRY,               0,               0,          0,          0,          0,          0,                     'Brother Paxton - OOC - Cast Renew on Stormwind Infantry'),

( @ACTION_LIST + 2, @SMART_TYPE_TIMED_ACTIONLIST,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           8000,           8000,              0,              0,              0,                   '',        @SMART_ACTION_CALL_TIMED_ACTIONLIST, @ACTION_LIST_STORMWIND_INFANTRY,                            0,                0,                0,               0,               0,               0, @SMART_TARGET_CREATURE_GUID,          279893, @ENTRY_STORMWIND_INFANTRY,               0,               0,          0,          0,          0,          0,                    'Brother Paxton - OOC - Trigger Stormwind Infantry Talk 3'),
( @ACTION_LIST + 2, @SMART_TYPE_TIMED_ACTIONLIST,    1,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,              0,              0,              0,              0,              0,                   '',               @SMART_ACTION_PAUSE_MOVEMENT,                               0,                         4000,                0,                0,               0,               0,               0,          @SMART_TARGET_SELF,               0,                         0,               0,               0,          0,          0,          0,          0,                                       'Brother Paxton - OOC - Pause Movement'),
( @ACTION_LIST + 2, @SMART_TYPE_TIMED_ACTIONLIST,    2,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           2000,           2000,              0,              0,              0,                   '',              @SMART_ACTION_SET_ORIENTATION,                               0,                            0,                0,                0,               0,               0,               0, @SMART_TARGET_CREATURE_GUID,          279893, @ENTRY_STORMWIND_INFANTRY,               0,               0,          0,          0,          0,          0,                              'Brother Paxton - OOC - Face Stormwind Infantry'),
( @ACTION_LIST + 2, @SMART_TYPE_TIMED_ACTIONLIST,    3,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           1000,           1000,              0,              0,              0,                   '',                         @SMART_ACTION_TALK,                  @TALK_GROUP_ID,                            0,                1,                0,               0,               0,               0,          @SMART_TARGET_SELF,               0,                         0,               0,               0,          0,          0,          0,          0,                                                'Brother Paxton - OOC - Say 2'),
( @ACTION_LIST + 2, @SMART_TYPE_TIMED_ACTIONLIST,    4,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           2000,           2000,              0,              0,              0,                   '',                         @SMART_ACTION_CAST,               @SPELL_FLASH_HEAL,                            0,                0,                0,               0,               0,               0, @SMART_TARGET_CREATURE_GUID,          279893, @ENTRY_STORMWIND_INFANTRY,               0,               0,          0,          0,          0,          0,                'Brother Paxton - OOC - Cast Flash Heal on Stormwind Infantry'),

( @ACTION_LIST + 3, @SMART_TYPE_TIMED_ACTIONLIST,    0,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           8000,           8000,              0,              0,              0,                   '',        @SMART_ACTION_CALL_TIMED_ACTIONLIST, @ACTION_LIST_STORMWIND_INFANTRY,                            0,                0,                0,               0,               0,               0, @SMART_TARGET_CREATURE_GUID,          279894, @ENTRY_STORMWIND_INFANTRY,               0,               0,          0,          0,          0,          0,                    'Brother Paxton - OOC - Trigger Stormwind Infantry Talk 4'),
( @ACTION_LIST + 3, @SMART_TYPE_TIMED_ACTIONLIST,    1,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,              0,              0,              0,              0,              0,                   '',               @SMART_ACTION_PAUSE_MOVEMENT,                               0,                         4000,                0,                0,               0,               0,               0,          @SMART_TARGET_SELF,               0,                         0,               0,               0,          0,          0,          0,          0,                                       'Brother Paxton - OOC - Pause Movement'),
( @ACTION_LIST + 3, @SMART_TYPE_TIMED_ACTIONLIST,    2,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           2000,           2000,              0,              0,              0,                   '',              @SMART_ACTION_SET_ORIENTATION,                               0,                            0,                0,                0,               0,               0,               0, @SMART_TARGET_CREATURE_GUID,          279894, @ENTRY_STORMWIND_INFANTRY,               0,               0,          0,          0,          0,          0,                              'Brother Paxton - OOC - Face Stormwind Infantry'),
( @ACTION_LIST + 3, @SMART_TYPE_TIMED_ACTIONLIST,    3,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           1000,           1000,              0,              0,              0,                   '',                         @SMART_ACTION_TALK,                  @TALK_GROUP_ID,                            0,                1,                0,               0,               0,               0,          @SMART_TARGET_SELF,               0,                         0,               0,               0,          0,          0,          0,          0,                                                'Brother Paxton - OOC - Say 5'),
( @ACTION_LIST + 3, @SMART_TYPE_TIMED_ACTIONLIST,    4,      0, @SMART_EVENT_UPDATE_OOC, @SMART_EVENT_PHASE_MASK_ALWAYS,            100, @SMART_EVENT_FLAG_NO_FLAG,           2000,           2000,              0,              0,              0,                   '',                         @SMART_ACTION_CAST,                  @SPELL_PENANCE,                            0,                0,                0,               0,               0,               0, @SMART_TARGET_CREATURE_GUID,          279894, @ENTRY_STORMWIND_INFANTRY,               0,               0,          0,          0,          0,          0,                   'Brother Paxton - OOC - Cast Penance on Stormwind Infantry');